"""initial migration

Revision ID: 6927d9711122
Revises: 
Create Date: 2025-03-22 17:59:43.111516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6927d9711122'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('START', 'CONDITION', 'RESULT', name='blocktype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('decision_value', sa.String(), nullable=True),
    sa.Column('next_block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_name', sa.String(), nullable=False),
    sa.Column('operator', sa.Enum('EQUAL', 'LOWER_THAN', 'LOWER_OR_EQUAL_THAN', 'GREATER_THAN', 'GREATER_OR_EQUAL_THAN', 'ELSE', name='conditioncriteria'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_block_id', sa.Integer(), nullable=False),
    sa.Column('next_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['next_block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_rules')
    op.drop_table('blocks')
    op.drop_table('policies')
    # ### end Alembic commands ###
